apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: selfish-hamster-go
  janus-idp.io/tekton: selfish-hamster-go
  backstage.io/kubernetes-id: selfish-hamster-go
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: selfish-hamster-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
