apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: selfish-hamster-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: selfish-hamster-go 
  name: selfish-hamster-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: selfish-hamster-go 
